trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: DotNetCoreCLI@2
  inputs:
    azureSubscription: 'pf0841g1 - Azure para Estudantes (f85ce35b-59c2-4fb8-9627-68c4aa18fcce)'
    command: 'build'
    projects: '**/*.csproj'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
- task: DotNetCoreCLI@2
  inputs:
    azureSubscription: 'pf0841g1 - Azure para Estudantes (f85ce35b-59c2-4fb8-9627-68c4aa18fcce)'
    command: 'publish'
    publishWebProjects: true
    workingDirectory: '$(System.DefaultWorkingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'app'
    publishLocation: 'Container'
- task: Docker@2
  inputs:
    containerRegistry: 'dotnetmssqlpf0841g1'
    repository: 'dotnetsql'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)
      latest