trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  RestoreBuildProjects: 'app/aspnetapp/aspnetapp.csproj'

steps:
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    azureSubscription: 'pf0841g1 - Azure para Estudantes (f85ce35b-59c2-4fb8-9627-68c4aa18fcce)'
    command: restore
    projects: '$(Parameters.RestoreBuildProjects)'
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    azureSubscription: 'pf0841g1 - Azure para Estudantes (f85ce35b-59c2-4fb8-9627-68c4aa18fcce)'
    projects: '$(Parameters.RestoreBuildProjects)'
    arguments: '--configuration $(BuildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    azureSubscription: 'pf0841g1 - Azure para Estudantes (f85ce35b-59c2-4fb8-9627-68c4aa18fcce)'
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
    zipAfterPublish: True
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: app
- task: Docker@2
  inputs:
    containerRegistry: 'dotnetmssqlpf0841g1'
    repository: 'dotnetsql'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)
      latest
